### ISSUE TITLE
Enhance Readme - Project Setup Instructions

### ISSUE THREAD

**Issue by CapTen101** [sambhav228/Student_Performance_Analysis#1]
### To begin with, we need to expand on the Readme first.
The following work will be be done which is distributed into various issues. It will be written in markdown only.

- [ ] Write a section about how to clone this particular repo.
- [ ] Write a section about how to add the remote.
- [ ] Write a section about how to add, commit and push your code to the repository.

-  Cloning is pretty-much the first step to start contributing to a project. Take help of this particular [CONTRIBUTING.md](https://github.com/CapTen101/Crop-Analyzer-AI/blob/master/CONTRIBUTING.md) file to get started and have some ideas as to how things are sone.

- Check this [repository here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) for having some look on **Markdown syntax**

**Comment by CapTen101** [comment]
@sambhav228 @Priyanknasit  We have to add all relevant git instructions for new-comers to follow

**Comment by sambhav228** [comment]
DONE @CapTen101

**Comment by CapTen101** [comment]
@sambhav228 oh right. I already added the instructions yesterday but forgot to close this. Thanks for reminding :)
