### ISSUE TITLE
Make a Pull Request Template for this repository

### ISSUE THREAD

**Issue by CapTen101** [sambhav228/Student_Performance_Analysis#3]
#### Check out resources here:

- [Creating a pull request template for your repository](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

#### Refer below issue templates for help:

- [Sample PR templates](https://github.com/CapTen101/the-turing-way/blob/master/.github/PULL_REQUEST_TEMPLATE.md) 
- [Sample PR template 2](https://github.com/CapTen101/CircuitVerseDocs/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by sambhav228** [comment]
Done 
checkout @ doc/pull_request-template.md
