### ISSUE TITLE
Finalize the workflow of the project

### ISSUE THREAD

**Issue by CapTen101** [sambhav228/Student_Performance_Analysis#6]
### We have to finalize the workflow/flowchart decided earlier.
Report it at the earliest. Only after that we can proceed further.
This is currently assigned to the project admin @sambhav228

**Comment by CapTen101** [comment]
Kindly finish this ASAP @sambhav228

**Comment by CapTen101** [comment]
Ok so this is the flowchart from @sambhav228 , as of now:
> Also uploaded here: [flowchart-PDF](https://github.com/sambhav228/Stulysis/blob/master/Assets/flowchart-Stulysis.pdf)

![flowchart-Stulysis-image-format](https://user-images.githubusercontent.com/45699327/88695737-f0a8b100-d11f-11ea-987e-2366cd0a4eb0.jpg)

**Comment by sambhav228** [comment]
Close this issue as of now

**Comment by CapTen101** [comment]
right
